


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_relatorios(object):
    def setupUi(self, relatorios):
        relatorios.setObjectName("relatorios")
        relatorios.resize(849, 600)
        relatorios.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.centralwidget = QtWidgets.QWidget(relatorios)
        self.centralwidget.setObjectName("centralwidget")
        self.bt_imprimir_relatorio = QtWidgets.QPushButton(self.centralwidget)
        self.bt_imprimir_relatorio.setGeometry(QtCore.QRect(630, 300, 191, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_imprimir_relatorio.sizePolicy().hasHeightForWidth())
        self.bt_imprimir_relatorio.setSizePolicy(sizePolicy)
        self.bt_imprimir_relatorio.setStyleSheet("background-color: rgb(26, 177, 106);")
        self.bt_imprimir_relatorio.setObjectName("bt_imprimir_relatorio")
        self.bt_sair_relatorio = QtWidgets.QPushButton(self.centralwidget)
        self.bt_sair_relatorio.setGeometry(QtCore.QRect(630, 540, 191, 41))
        self.bt_sair_relatorio.setStyleSheet("background-color: rgb(152, 38, 38);")
        self.bt_sair_relatorio.setObjectName("bt_sair_relatorio")
        self.ln_cpf_aluguel = QtWidgets.QLineEdit(self.centralwidget)
        self.ln_cpf_aluguel.setGeometry(QtCore.QRect(30, 70, 481, 41))
        self.ln_cpf_aluguel.setObjectName("ln_cpf_aluguel")
        self.ln_placa_aluguel = QtWidgets.QLineEdit(self.centralwidget)
        self.ln_placa_aluguel.setGeometry(QtCore.QRect(30, 130, 481, 41))
        self.ln_placa_aluguel.setObjectName("ln_placa_aluguel")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 20, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(540, 90, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(17)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.bt_pagamento = QtWidgets.QComboBox(self.centralwidget)
        self.bt_pagamento.setGeometry(QtCore.QRect(540, 130, 271, 41))
        self.bt_pagamento.setObjectName("bt_pagamento")
        self.bt_pagamento.addItem("")
        self.bt_pagamento.addItem("")
        self.bt_pagamento.addItem("")
        self.bt_inserir_aluguel = QtWidgets.QPushButton(self.centralwidget)
        self.bt_inserir_aluguel.setGeometry(QtCore.QRect(30, 210, 371, 41))
        self.bt_inserir_aluguel.setObjectName("bt_inserir_aluguel")
        self.bt_exc_aluguel = QtWidgets.QPushButton(self.centralwidget)
        self.bt_exc_aluguel.setGeometry(QtCore.QRect(450, 210, 371, 41))
        self.bt_exc_aluguel.setObjectName("bt_exc_aluguel")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScrollBar.setGeometry(QtCore.QRect(790, 360, 20, 161))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.ln_pesquisa = QtWidgets.QLineEdit(self.centralwidget)
        self.ln_pesquisa.setGeometry(QtCore.QRect(30, 300, 601, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ln_pesquisa.setFont(font)
        self.ln_pesquisa.setObjectName("ln_pesquisa")
        self.lb_resultado = QtWidgets.QLabel(self.centralwidget)
        self.lb_resultado.setGeometry(QtCore.QRect(26, 356, 791, 181))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(14)
        self.lb_resultado.setFont(font)
        self.lb_resultado.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lb_resultado.setText("")
        self.lb_resultado.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lb_resultado.setIndent(16)
        self.lb_resultado.setObjectName("lb_resultado")
        relatorios.setCentralWidget(self.centralwidget)

        self.retranslateUi(relatorios)
        QtCore.QMetaObject.connectSlotsByName(relatorios)

    def retranslateUi(self, relatorios):
        _translate = QtCore.QCoreApplication.translate
        relatorios.setWindowTitle(_translate("relatorios", "MainWindow"))
        self.bt_imprimir_relatorio.setText(_translate("relatorios", "IMPRIMIR RELATORIO"))
        self.bt_sair_relatorio.setText(_translate("relatorios", "SAIR"))
        self.ln_cpf_aluguel.setPlaceholderText(_translate("relatorios", "     CPF DO CLIENTE"))
        self.ln_placa_aluguel.setPlaceholderText(_translate("relatorios", "    PLACA DO CARRO"))
        self.label.setText(_translate("relatorios", "INSERIR ALUGUEL DE VEICULO"))
        self.label_2.setText(_translate("relatorios", "FORMA DE PAGAMENTO:"))
        self.bt_pagamento.setItemText(0, _translate("relatorios", "CARTAO DE CREDITO"))
        self.bt_pagamento.setItemText(1, _translate("relatorios", "DINHEIRO"))
        self.bt_pagamento.setItemText(2, _translate("relatorios", "DEBITO"))
        self.bt_inserir_aluguel.setText(_translate("relatorios", "INSERIR ALUGUEL"))
        self.bt_exc_aluguel.setText(_translate("relatorios", "EXCLUIR ALUGUEL"))
        self.ln_pesquisa.setPlaceholderText(_translate("relatorios", "     INFORME UM CPF PARA A PESQUISA"))
