


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ln_placa = QtWidgets.QLineEdit(self.centralwidget)
        self.ln_placa.setGeometry(QtCore.QRect(460, 60, 271, 41))
        self.ln_placa.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_placa.setObjectName("ln_placa")
        self.ln_modelo = QtWidgets.QLineEdit(self.centralwidget)
        self.ln_modelo.setGeometry(QtCore.QRect(130, 130, 601, 41))
        self.ln_modelo.setObjectName("ln_modelo")
        self.ln_descricao = QtWidgets.QLineEdit(self.centralwidget)
        self.ln_descricao.setGeometry(QtCore.QRect(130, 200, 601, 41))
        self.ln_descricao.setObjectName("ln_descricao")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 60, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.bt_cadaastro_car = QtWidgets.QPushButton(self.centralwidget)
        self.bt_cadaastro_car.setGeometry(QtCore.QRect(130, 280, 261, 41))
        self.bt_cadaastro_car.setObjectName("bt_cadaastro_car")
        self.bt_del_car = QtWidgets.QPushButton(self.centralwidget)
        self.bt_del_car.setGeometry(QtCore.QRect(320, 360, 261, 41))
        self.bt_del_car.setObjectName("bt_del_car")
        self.bt_editar_car = QtWidgets.QPushButton(self.centralwidget)
        self.bt_editar_car.setGeometry(QtCore.QRect(470, 280, 261, 41))
        self.bt_editar_car.setObjectName("bt_editar_car")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(40, 534, 101, 31))
        self.pushButton_4.setStyleSheet("alternate-background-color: rgb(152, 38, 38);\n"
"background-color: rgb(173, 127, 168);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(300, 410, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(15)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ln_placa.setPlaceholderText(_translate("MainWindow", "2603-HNP"))
        self.ln_modelo.setPlaceholderText(_translate("MainWindow", "     MODELO DO VEICULO"))
        self.ln_descricao.setPlaceholderText(_translate("MainWindow", "     DESCRIÇÃO"))
        self.label.setText(_translate("MainWindow", "PLACA DO CARRO:"))
        self.bt_cadaastro_car.setText(_translate("MainWindow", "CADASTRAR NOVO CARRO"))
        self.bt_del_car.setText(_translate("MainWindow", "REMOVER CARRO"))
        self.bt_editar_car.setText(_translate("MainWindow", "EDITAR DADOS DO CARRO"))
        self.pushButton_4.setText(_translate("MainWindow", "voltar"))
